name: 'Run precommit hooks'

runs:
  using: "composite"
  steps:
    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dos2unix
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y dos2unix

    - name: run precommit hooks
      shell: bash
      run: |
        Rscript -e 'install.packages("devtools")'
        Rscript -e 'devtools::install()'
        Rscript -e 'Rprecommit::install_precommit(force=TRUE)'
        Rscript -e 'Rprecommit::run_precommit()'
