name: 'Run precommit hooks'

runs:
  steps:
    - name: run precommit hooks
      shell: bash
      run: |
        Rscript -e 'install.packages("devtools")'
        Rscript -e 'devtools::install()'
        Rscript -e 'Rprecommit::install_precommit(force=TRUE)'
        Rscript -e 'Rprecommit::run_precommit()'
