repos:
  - repo: local
    hooks:
      - id: renv
        name: Synchronize project from renv.lock
        description: Synchronize the project from the renv.lock
        entry: Rscript inst/pre-commit/hooks/synchronize_project.R
        language: r
        additional_dependencies: [cli]
        pass_filenames: false
      - id: styler
        name: Format package with styler
        description: Styler formats your code according to the tidyverse style guide
        entry: Rscript inst/pre-commit/hooks/format_package_with_styler.R
        language: r
        additional_dependencies: [cli, styler]
        pass_filenames: false
      - id: linter
        name: Format package with linter
        description: Linter checks style, syntax errors and possible semantic issues
        entry: Rscript inst/pre-commit/hooks/format_package_with_linter.R
        language: r
        additional_dependencies: [cli, linter]
        pass_filenames: false
      - id: covr
        name: Check coverage
        description: Test coverage for your R package
        entry: Rscript inst/pre-commit/hooks/check_coverage.R
        language: r
        additional_dependencies: [cli, covr]
        pass_filenames: false
