repos:
  - repo: local
    hooks:
    - id: renv
      name: renv
      description: Synchronize the project from the renv.lock
      entry: Rscript inst/hooks/synchronize_project.R
      language: r
