repos:
  - repo: local
    hooks:
    - id: lintr
      name: lintr
      description: Runs lintr on R filesqc
      entry: Rscript inst/hooks/exported/lintr.R
      language: r
      files: '(\.[rR]profile|\.R|\.Rmd|\.Rnw|\.r|\.rmd|\.rnw|\.[qQ]md)$'
      exclude: 'renv/activate\.R'
