name: Run pre-commit hooks

on:
  pull_request:
    branches: [main, master]

jobs:
  run-precommit-hooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run precommit hooks
        uses: ./.github/actions/run-precommit-hooks
        with:
          target: "master"
          source: ${{ github.head_ref }}
