name: Run pre-commit hooks

on:
  pull_request:
    branches: [main, master]

run-precommit-hooks:
  steps:
    - uses: actions/checkout@v4
    - name: Run precommit hooks
      uses: ./.github/actions/run-precommit-hooks
      with:
        target: [main, master]
        source: ${{ github.head_ref }}
